// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fv
double fv(double pv, double i, int n);
RcppExport SEXP _finecn_fv(SEXP pvSEXP, SEXP iSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pv(pvSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fv(pv, i, n));
    return rcpp_result_gen;
END_RCPP
}
// pv
double pv(double fv, double i, int n);
RcppExport SEXP _finecn_pv(SEXP fvSEXP, SEXP iSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(pv(fv, i, n));
    return rcpp_result_gen;
END_RCPP
}
// fvannuity
double fvannuity(double cf, int n, double m, double i, double p);
RcppExport SEXP _finecn_fvannuity(SEXP cfSEXP, SEXP nSEXP, SEXP mSEXP, SEXP iSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type cf(cfSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fvannuity(cf, n, m, i, p));
    return rcpp_result_gen;
END_RCPP
}
// pvannuity
double pvannuity(double cf, double i, int n);
RcppExport SEXP _finecn_pvannuity(SEXP cfSEXP, SEXP iSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type cf(cfSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(pvannuity(cf, i, n));
    return rcpp_result_gen;
END_RCPP
}
// capm
double capm(double rf, double b, double mp);
RcppExport SEXP _finecn_capm(SEXP rfSEXP, SEXP bSEXP, SEXP mpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rf(rfSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mp(mpSEXP);
    rcpp_result_gen = Rcpp::wrap(capm(rf, b, mp));
    return rcpp_result_gen;
END_RCPP
}
// capmValue
void capmValue(double capm, double expR);
RcppExport SEXP _finecn_capmValue(SEXP capmSEXP, SEXP expRSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type capm(capmSEXP);
    Rcpp::traits::input_parameter< double >::type expR(expRSEXP);
    capmValue(capm, expR);
    return R_NilValue;
END_RCPP
}
// geom_Bar
double geom_Bar(NumericVector x);
RcppExport SEXP _finecn_geom_Bar(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(geom_Bar(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_finecn_fv", (DL_FUNC) &_finecn_fv, 3},
    {"_finecn_pv", (DL_FUNC) &_finecn_pv, 3},
    {"_finecn_fvannuity", (DL_FUNC) &_finecn_fvannuity, 5},
    {"_finecn_pvannuity", (DL_FUNC) &_finecn_pvannuity, 3},
    {"_finecn_capm", (DL_FUNC) &_finecn_capm, 3},
    {"_finecn_capmValue", (DL_FUNC) &_finecn_capmValue, 2},
    {"_finecn_geom_Bar", (DL_FUNC) &_finecn_geom_Bar, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_finecn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
