# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Future Value of a cash flow
#'
#'Provide the present value, interest rate, and number of periods
#'
#'@name fv
#'
#'
#'@param pv the present value of a cash flow
#'@param i the annual interest rate
#'@param n the number of periods
#'
#'@return Future Value
#'
#'
#'@export fv
fv <- function(pv, i, n) {
    .Call(`_finecn_fv`, pv, i, n)
}

#'Present Value of a cash flow
#'
#'Provide the future value, interest rate, and number of periods to get the present value needed
#'
#'@name pv
#'
#'
#'@param fv the future value of a cash flow
#'@param i the annual interest rate
#'@param n the number of periods
#'
#'@return Present Value
#'
#'
#'@export pv
pv <- function(fv, i, n) {
    .Call(`_finecn_pv`, fv, i, n)
}

#'Future Value of an ordinary annuity
#'
#'Provide the cash flow, interest rate, and number of periods
#'
#'@name fvannuity
#'
#'
#'@param cf the present value of a cash flow
#'@param i the annual interest rate
#'@param n the number of years
#'@param m the number of periods in a year
#'@param p an optional parameter to divide the number of
#'
#'@return Future Value
#'
#'
#'@export fvannuity
fvannuity <- function(cf, n, m, i, p = 1.0) {
    .Call(`_finecn_fvannuity`, cf, n, m, i, p)
}

#'Present Value of an ordinary annuity
#'
#'Provide the cash flow, interest rate, and number of periods
#'
#'@name fvannuity
#'
#'
#'@param cf the present value of a cash flow
#'@param i the annual interest rate
#'@param n the number of years
#'
#'@return Present Value
#'
#'
#'@export pvannuity
pvannuity <- function(cf, i, n) {
    .Call(`_finecn_pvannuity`, cf, i, n)
}

#'Expected return of a stock based on capm
#'
#'Provide the risk-free rate of return, beta, and market premium to calculate the expected market return
#'
#'@name capm
#'
#'
#'@param rf the risk free rate of return
#'@param b beta for the interested stock
#'@param mp the market premium rate
#'
#'@return capm expected return
#'
#'
#'@export capm
capm <- function(rf, b, mp) {
    .Call(`_finecn_capm`, rf, b, mp)
}

#'Value of a stock based on capm analysis
#'
#'Provide the expected return and the capm return to determine the value of a stock using fundamental analysis
#'
#'@name capmValue
#'
#'
#'@param capm the return according to capm
#'@param expR the expected return for the stock
#'
#'@return the stock's position
#'
#'
#'@export capmValue
capmValue <- function(capm, expR) {
    invisible(.Call(`_finecn_capmValue`, capm, expR))
}

#'Expected return of a stock based on the geometric mean
#'
#'Provide the percentage change in the price of a stock to calculate the expected geometric return
#'
#'@name geom_Bar
#'
#'
#'@param x a vector containing the daily percent changes in price for a stock
#'
#'@return expected return of a stock
#'
#'
#'@export geom_Bar
geom_Bar <- function(x) {
    .Call(`_finecn_geom_Bar`, x)
}

